image: atlassian/default-image:4

clone:
  enabled: true

pipelines:
  default:
    - step:
        name: Build and push the base Docker image
        services:
          - docker
        script:
          - echo "Logging into Docker Hub"
          - docker login -u "$dockername" --password-stdin <<< "$dockertoken"
          - echo "Installing the devcontainer cli"
          - npm install -g @devcontainers/cli
          - echo "Building the container"
          - devcontainer build --workspace-folder ./dind-with-node --image-name oct8l/devcontainers:dind-latest
          - echo "Pushing Docker image to Docker Hub"
          - docker push oct8l/devcontainers:dind-latest
