image: atlassian/default-image:4

clone:
  enabled: true

pipelines:
  default:
    - step:
        name: Build and push the main builder image
        services:
          - docker
        script:
          - echo "Installing the devcontainer cli"
          - npm install -g @devcontainers/cli
          - echo "Building the container"
          - devcontainer build --workspace-folder ./dind-with-node --image-name oct8l/dind-with-node:latest:dind-latest
          - echo "Logging into Docker Hub"
          - docker login -u "$dockername" --password-stdin <<< "$dockertoken"
          - echo "Pushing Docker image to Docker Hub"
          - docker push oct8l/devcontainers:dind-latest
        trigger: automatic
        condition:
          changesets:
            includePaths:
              - "dind-with-node/.devcontainer/devcontainer.json"
    - step:
        name: Build and push the Python and Selenium image
        services:
          - docker
        script:
          - echo "Installing the devcontainer cli"
          - npm install -g @devcontainers/cli
          - echo "Building the container"
          - devcontainer build --workspace-folder ./python-selenium --image-name oct8l/devcontainers:python-selenium-latest
          - echo "Logging into Docker Hub"
          - docker login -u "$dockername" --password-stdin <<< "$dockertoken"
          - echo "Pushing Docker image to Docker Hub"
          - docker push oct8l/devcontainers:python-selenium-latest
        trigger: automatic
        condition:
          changesets:
            includePaths:
              - "python-selenium/.devcontainer/devcontainer.json"
              - "python-selenium/Dockerfile"
