image: atlassian/default-image:4

clone:
  enabled: true

pipelines:
  default:
    - parallel:
      - step:
          name: Build and push the main builder image
          services:
            - docker
          caches:
            - docker
          runs-on:
            - self.hosted
          script:
            - export DOCKER_BUILDKIT=1
            - echo "Installing the devcontainer cli"
            - npm install -g @devcontainers/cli
            - echo "Logging into Docker Hub"
            - docker login -u "$dockername" --password-stdin <<< "$dockertoken"
            - echo "Build the containers and manifest"
            - sh ./build-scripts/build_dind-with-node.sh
          trigger: automatic
          condition:
            changesets:
              includePaths:
                - "dind-with-node/.devcontainer/devcontainer.json"
      - step:
          name: Build and push the Python and Selenium image
          services:
            - docker
          caches:
            - docker
          runs-on:
            - self.hosted
          script:
            - export DOCKER_BUILDKIT=1
            - docker buildx create --name builder123 --use
            - docker buildx inspect --bootstrap
            - echo "Some debugging output"
            - docker images
            - docker buildx version
            - docker buildx ls
            - echo "Installing the devcontainer cli"
            - npm install -g @devcontainers/cli
            - echo "Logging into Docker Hub"
            - docker login -u "$dockername" --password-stdin <<< "$dockertoken"
            - echo "Build the containers and manifest"
            - sh ./build-scripts/build_python-selenium.sh
          trigger: automatic
          condition:
            changesets:
              includePaths:
                - "python-selenium/.devcontainer/devcontainer.json"
                - "python-selenium/Dockerfile"
